<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMenu.Master" AutoEventWireup="true" CodeBehind="AnnounceAdmin.aspx.cs" Inherits="Callboard.AnnounceAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

   
        <div class="row justify-content-center">
            <h2 class="title text-center mb-4">Таблиця "Книги"</h2>
        </div>
        <div class="row">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/admin">Адмін-панель</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Таблиця "Книги"</li>
              </ol>
            </nav>
            <a href="/admin/book/create" class="btn btn-default ml-3"><i class="fas fa-plus"></i> <strong>Додати книгу</strong></a>
        </div>

        <div class="row">

        <div class="col-sm-8 col-md-12 col-lg-12">


        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
            ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>"
             DeleteCommand="DELETE FROM announcements WHERE id = @id"
            UpdateCommand="Update announcements SET title=@title, user_id=@user_id, subcategory_id=@subcategory_id, city_id=@city_id,
            image_name=@image_name, creation_date=@creation_date, message_text=@message_text, price=@price WHERE id=@id"
          
            SelectCommand="SELECT * FROM announcements">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="Int32" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="title" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
                <asp:Parameter Name="subcategory_id" Type="Int32" />
                <asp:Parameter Name="city_id" Type="Int32" />
                <asp:Parameter Name="image_name" Type="String" />
                <asp:Parameter Name="creation_date" Type="DateTime" />
                <asp:Parameter Name="message_text" Type="String" />
                <asp:Parameter Name="price" Type="Decimal" />
                <asp:Parameter Name="id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

         <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>" 
                                 SelectCommand="SELECT id, CONCAT(users.first_name,' ',users.last_name) as user_name FROM users"
                                 EnableCaching="True"></asp:SqlDataSource>
         <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>" 
                                 SelectCommand="SELECT id, name as subcategory_name FROM subcategories"
                                 EnableCaching="True"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>" 
                                 SelectCommand="SELECT id, name as city_name FROM cities"
                                 EnableCaching="True"></asp:SqlDataSource>

        <%--<asp:GridView ID="gridEmployees" runat="server" DataSourceID="SqlDataSource1" DataKeyNames="id"
            AutoGenerateColumns="false" PageSize="4" CssClass="table table-striped table-bordered table-condensed">
             <HeaderStyle CssClass="thead-dark" />
            <RowStyle  />
            <PagerStyle /> 
                <Columns>
                    <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
                    <asp:BoundField HeaderText="ID" DataField="id" ReadOnly="True" />
                    <asp:BoundField HeaderText="Назва" DataField="title" />
                    <asp:BoundField HeaderText="Код користувача" DataField="user_id" />
                    <asp:BoundField HeaderText="Код підкатегорії" DataField="subcategory_id" />
                    <asp:BoundField HeaderText="Код міста" DataField="city_id" />
                    <asp:BoundField HeaderText="Назва зображення" DataField="image_name" />
                    <asp:BoundField HeaderText="Час створення" DataField="creation_date" />
                    <asp:BoundField HeaderText="Текст оголошення" DataField="message_text" />
                    <asp:BoundField HeaderText="Ціна" DataField="price" />
                </Columns>
        </asp:GridView>--%>

                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"  
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id"  
            onrowcancelingedit="GridView1_RowCancelingEdit"   
            onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
            onrowupdating="GridView1_RowUpdating" BackColor="White"   
            BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" HeaderStyle-Width="100px" 
            CellSpacing="1" GridLines="None" >  
            <Columns>  
                 <asp:TemplateField HeaderText="ID">  
                    <ItemTemplate>  
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("id") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField>  
                <asp:TemplateField HeaderText="Назва">
                    <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left" Wrap="False"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:TextBox ID="TextBox2" class="form-control" runat="server" Text='<%# Bind("title") %>'></asp:TextBox>  
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBox2" ForeColor="Red" ErrorMessage="Поле назва не може бути пустим"></asp:RequiredFieldValidator>  
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("title") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField>  
                <asp:TemplateField HeaderText="Код користувача">
                    <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left" Wrap="False"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:DropDownList ID="DropDownList1" runat="server" class="form-control" DataSourceID="SqlDataSource2" SelectedValue='<%# Bind("user_id") %>' AppendDataBoundItems="True"
                         DataTextField="user_name" DataValueField="id"></asp:DropDownList>
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("user_id") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Код підкатегорії">
                    <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left" Wrap="False"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:DropDownList ID="DropDownList2" runat="server" class="form-control" DataSourceID="SqlDataSource3" SelectedValue='<%# Bind("subcategory_id") %>' AppendDataBoundItems="True"
                         DataTextField="subcategory_name" DataValueField="id"></asp:DropDownList>
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("subcategory_id") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField> 
                <asp:TemplateField HeaderText="Код міста">
                    <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left" Wrap="False"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSource4" class="form-control"  SelectedValue='<%# Bind("city_id") %>' AppendDataBoundItems="True"
                         DataTextField="city_name" DataValueField="id"></asp:DropDownList>
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("city_id") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField>  
                <asp:TemplateField HeaderText="Назва зображення">
                    <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left" Wrap="False"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:TextBox ID="TextBox3" runat="server" class="form-control" Text='<%# Bind("image_name") %>'></asp:TextBox>  
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="TextBox3" ForeColor="Red" ErrorMessage="Поле назва не може бути пустим"></asp:RequiredFieldValidator>  
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ValidationExpression=".+[.].{,8}" ControlToValidate="TextBox3" ForeColor="Red" ErrorMessage="Неправильний формат запису"></asp:RegularExpressionValidator>
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("image_name") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField> 
                 <asp:TemplateField HeaderText="Час створення">
                     <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left" Wrap="False"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:TextBox ID="TextBox4" runat="server" class="form-control" Text='<%# Bind("creation_date") %>' TextMode="DateTime"></asp:TextBox>  
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="TextBox3" ForeColor="Red" ErrorMessage="Поле назва не може бути пустим"></asp:RequiredFieldValidator>  
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("creation_date") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField> 
                <asp:TemplateField HeaderText="Текст оголошення">
                    <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:TextBox ID="TextBox5" runat="server" class="form-control" Text='<%# Bind("message_text") %>' TextMode="MultiLine" Rows="4"></asp:TextBox>  
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="TextBox3" ForeColor="Red" ErrorMessage="Поле не може бути пустим"></asp:RequiredFieldValidator>  
                   </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("message_text") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField> 
                <asp:TemplateField HeaderText="Ціна">
                    <HeaderStyle Width="100px" HorizontalAlign="Left" Wrap="False"></HeaderStyle>
                    <ItemStyle Width="100px" HorizontalAlign="Left" Wrap="False"></ItemStyle>
                    <EditItemTemplate>  
                        <asp:TextBox ID="TextBox6" runat="server" class="form-control" Text='<%# Bind("price") %>'></asp:TextBox>  
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="TextBox3" ForeColor="Red" ErrorMessage="Поле не може бути пустим"></asp:RequiredFieldValidator>  
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ValidationExpression="\d*([.,]\d{1,2})?" ControlToValidate="TextBox3" ForeColor="Red" ErrorMessage="Неправильний формат запису"></asp:RegularExpressionValidator>
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:Label ID="Label10" runat="server" Text='<%# Bind("price") %>'></asp:Label>  
                    </ItemTemplate>  
                </asp:TemplateField>


            </Columns>  
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />  
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />  
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />  
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />  
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />  
            <SortedAscendingCellStyle BackColor="#F1F1F1" />  
            <SortedAscendingHeaderStyle BackColor="#594B9C" />  
            <SortedDescendingCellStyle BackColor="#CAC9C9" />  
            <SortedDescendingHeaderStyle BackColor="#33276A" />  
        </asp:GridView>  
        <asp:ValidationSummary ID="ValidationSummary1" ForeColor="Red" runat="server" />  
      

    </div>
</div>
</asp:Content>
