<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMenu.Master" AutoEventWireup="true" CodeBehind="index.aspx.cs" Inherits="Callboard.index" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <%--<asp:Repeater ID="Repeater1" runat="server"></asp:Repeater>--%>

    <asp:SqlDataSource ID="AnnounceData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>" 
        SelectCommand="SELECT announcements.id as id, title, user_id, announcements.subcategory_id as subcategory_id, subcategories.name as subcategory_name,
                        categories.name as category_name, categories.id as category_id,
                        city_id, image_name, cities.name as city_name, regions.name as region_name, creation_date, message_text, price FROM announcements
                        INNER JOIN subcategories ON subcategories.id = announcements.subcategory_id
                        INNER JOIN categories ON subcategories.category_id = categories.id
                        INNER JOIN cities ON cities.id = announcements.city_id
                        INNER JOIN regions ON regions.id = cities.region_id"></asp:SqlDataSource>
    <asp:SqlDataSource ID="CategoryData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>" 
        SelectCommand="SELECT categories.id as category_id, categories.name as category_name FROM categories;"></asp:SqlDataSource>

   <%-- <asp:SqlDataSource ID="CityData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>" 
        SelectCommand="SELECT cities.id as city_id, cities.name as city_name FROM cities"></asp:SqlDataSource>

     <asp:SqlDataSource ID="SubcategoryData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DatabaseConnectionString %>" 
        SelectCommand="SELECT subcategories.id as subcategory_id, subcategories.name as subcategory_name FROM subcategories
         WHERE subcategories.category_id = @CategoryId">
         <SelectParameters>
		     <asp:ControlParameter ControlID="DropDownList1" Name="CategoryId" PropertyName="SelectedValue" />
	    </SelectParameters>
        </asp:SqlDataSource>--%>


    <%--<asp:GridView ID="GridView2" runat="server" DataSourceID="AnnounceData"
	AutoGenerateDeleteButton="True" DataKeyNames="id" AutoGenerateColumns="False" >
        <Columns>
            <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
            <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
            <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
            <asp:BoundField DataField="category_id" HeaderText="category_id" SortExpression="category_id" />
            <asp:BoundField DataField="creation_date" HeaderText="creation_date" SortExpression="creation_date" />
            <asp:BoundField DataField="message_text" HeaderText="message_text" SortExpression="message_text" />
            <asp:BoundField DataField="image_name" HeaderText="image_name" SortExpression="image_name" />
        </Columns>
    </asp:GridView>--%>


    

     <%--<div class="col-sm-4 col-md-4 col-lg-4">
         <div class="card">
            <div class="card-header">Рубрики об’яв</div>
            <div class="card-body">
                <asp:DropDownList ID="DropDownList1" class="form-control card-title" runat="server" DataSourceID="CategoryData"  DataValueField="category_id" DataTextField="category_name"></asp:DropDownList>
            </div>
         </div>
      </div>--%>
     <%-- <div class="col-sm-4 col-md-4 col-lg-4">
         <div class="card">
            <div class="card-header">Населені пункти</div>
            <div class="card-body">
                <asp:DropDownList ID="DropDownList2" class="form-control card-title" runat="server" DataSourceID="CityData"  DataValueField="city_id" DataTextField="city_name"></asp:DropDownList>
            </div>
         </div>
      </div>--%>
    
    
    <div class="row">

    <div class="col-sm-3 col-md-3 col-lg-3">
    <asp:Repeater id="RepeaterMenu" runat="server" DataSourceID="CategoryData">
        <HeaderTemplate>
          <div class="card">
            <div class="card-header"><h5><strong>Категорії об’яв</strong></h5></div>
               <div class="list-group list-group-flush">
        </HeaderTemplate>
        <ItemTemplate>
            <a href='<%#string.Format("index.aspx?search_by_category_id={0}", Eval("category_id"))%>' class="menu-item list-group-item list-group-item-action">
                <%#DataBinder.Eval(Container.DataItem, "category_name") %>
            </a>
        </ItemTemplate>
        <FooterTemplate>
              </div>
          </div>
       </FooterTemplate>
</asp:Repeater>
</div>

    <div class="col-sm-9 col-md-9 col-lg-9">
    <div class="row justify-content-center my-3">
          <div class="col-sm-7 col-md-7 col-lg-7">
              <asp:TextBox ID="Search" runat="server" class="form-control" placeholder="Пошук" aria-label="Search" AutoPostBack="true"></asp:TextBox>
          </div>
           <div class="col-sm-2 col-md-2 col-lg-2">
               <asp:Button ID="Button3" runat="server" Text="Пошук" class="btn btn-outline-success btn-block my-2 my-sm-0" type="submit" OnClick="Button3_Click"/>
          </div> 
        </div>


       <% if (this.announcements.Tables[0].Rows.Count == 0) {%>
        <div class="row justify-content-center">
           <div class="col-sm-9 col-md-9 col-lg-9 my-2">
                 На жаль нічого не знайдено. <i class="far fa-frown-open"></i>
           </div>
        </div>
        <%} %>

       <asp:Repeater id="RepeaterItems" runat="server">
         
          <ItemTemplate>
              <div class="row justify-content-center">
                  <div class="img-container col-sm-9 col-md-9 col-lg-9 rounded my-2">
                      <div class="row">
                         <asp:Image ID="ItemImage" runat="server" CssClass="img-item my-3" ImageUrl='<%# string.Format("~/images/{0}", Eval("image_name")) %>' />
                        <div class="col-sm-12 col-md-7 col-lg-7">
                           <div class="row pt-2">
                               <div class="col-sm-12 col-md-12 col-lg-12 text-truncate">
                                    <asp:Label runat="server" ID="ItemTitle" CssClass="title" Text='<%#DataBinder.Eval(Container.DataItem, "title") %>' ></asp:Label>
                               </div>       
                           </div>
                            <div class="row py-3">
                                <div class="col-sm-12 col-md-12 col-lg-12">
                                    <asp:Label runat="server" ID="Label1" CssClass="m-price" Text='<%# (Eval("price").ToString() != "")? string.Format("{0} грн.", Eval("price")) : " &nbsp;" %>'></asp:Label>
                               </div>    
                           </div>
                            <div class="row pt-2">
                                <div class="col-sm-12 col-md-12 col-lg-12">
                                     <div class="float-left">
                                        <asp:Label runat="server" ID="Label2" class="m-attr" Text='<%#DataBinder.Eval(Container.DataItem, "category_name") %>' ></asp:Label>
                                    </div>
                                     <div class="float-left">
                                        <asp:Label runat="server" ID="Label4" class="m-attr-next" Text='<%#DataBinder.Eval(Container.DataItem, "subcategory_name") %>' ></asp:Label>
                                    </div>
                                </div>
                                
                           </div>
                            <div class="row pt-2">
                                <div class="col-sm-6 col-md-6 col-lg-6">
                                    <i class="far fa-clock"></i>
                                    <asp:Label runat="server" ID="Label3" class="m-attr" Text='<%#DataBinder.Eval(Container.DataItem, "creation_date") %>' ></asp:Label>
                                </div>
                                <div class="col-sm-6 col-md-6 col-lg-6 text-truncate">
                                    <i class="fas fa-map-marker-alt"></i>
                                    <asp:Label runat="server" ID="Label5" class="m-attr" Text='<%#DataBinder.Eval(Container.DataItem, "city_name") %>' ></asp:Label>
                                </div>
                           </div>
                        </div>

                      </div>
      
                  </div>
              </div>
              
          </ItemTemplate>
                     
       </asp:Repeater>
</div>
</div>


</asp:Content>
