
USE callboard;


CREATE TABLE options(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
name VARCHAR(150),
value VARCHAR(150)
);

CREATE TABLE types(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
name VARCHAR(150),
);

CREATE TABLE subjects(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
topic INT NOT NULL,
name VARCHAR(150)
);

CREATE TABLE roles(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
name VARCHAR(150) NOT NULL
);

CREATE TABLE users(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
patronymic VARCHAR(100) NOT NULL,
contact VARCHAR(200),
role_id INT FOREIGN KEY REFERENCES roles(id) NOT NULL,
creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
subject_id INT FOREIGN KEY REFERENCES subjects(id) NOT NULL,
user_id INT FOREIGN KEY REFERENCES users(id) NOT NULL,
type_id INT FOREIGN KEY REFERENCES types(id) NOT NULL,
creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
message_text TEXT
);

CREATE TABLE mail(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
user_id INT FOREIGN KEY REFERENCES users(id) NOT NULL,
email VARCHAR(80) NOT NULL,
is_active TINYINT NOT NULL
);


CREATE TABLE mail_subscribe(
id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
mail_id INT FOREIGN KEY REFERENCES mail(id) NOT NULL,
subject_id INT FOREIGN KEY REFERENCES subjects(id) NOT NULL,
);


